# Generated by Django 4.2.7 on 2023-12-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_pet_age_pet_vaccunes_alter_pet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(choices=[('LAB', 'Labrador'), ('PUG', 'Carlino'), ('BGL', 'Beagle'), ('BLD', 'Bulldog'), ('PERS', 'Persa'), ('SIAM', 'Siamés'), ('MCO', 'Maine Coon'), ('RGD', 'Ragdoll')], default='LAB', max_length=4),
        ),
        migrations.AddField(
            model_name='pet',
            name='category',
            field=models.CharField(choices=[('DOG', 'Perro'), ('CAT', 'Gato')], default='DOG', max_length=4),
        ),
    ]
