# Generated by Django 4.2.7 on 2023-12-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0008_alter_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(choices=[('LAB', 'Labrador'), ('PUG', 'Carlino'), ('BGL', 'Beagle'), ('BLD', 'Bulldog'), ('PERS', 'Persa'), ('SMS', 'Siamés'), ('MCO', 'Maine Coon'), ('RGL', 'Ragdoll')], default='BLD', max_length=4),
        ),
    ]
