# Generated by Django 4.2.7 on 2023-12-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0010_alter_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(default='kora', upload_to='Petmaze/petmaze/static/images'),
        ),
    ]
