# Generated by Django 4.2.7 on 2023-12-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0011_alter_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='description',
            field=models.TextField(help_text='Descripción de la venta.', null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='discount',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento de la venta.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Indica si la venta está habilitada o no.', null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Precio de la venta.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(choices=[('LAB', 'Labrador'), ('PUG', 'Carlino'), ('BGL', 'Beagle'), ('BLD', 'Bulldog'), ('PERS', 'Persa'), ('SMS', 'Siamés'), ('MCO', 'Maine Coon'), ('RGL', 'Ragdoll')], default='BLD', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='category',
            field=models.CharField(choices=[('DOG', 'Perro'), ('CAT', 'Gato')], default='DOG', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(default='kora', null=True, upload_to='Petmaze/petmaze/static/images'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
