# Generated by Django 4.2.7 on 2023-12-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0012_pet_description_pet_discount_pet_enabled_pet_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(choices=[('LAB', 'Labrador'), ('PUG', 'Carlino'), ('BGL', 'Beagle'), ('BLD', 'Bulldog'), ('PERS', 'Persa'), ('SMS', 'Siamés'), ('MCO', 'Maine Coon'), ('RGL', 'Ragdoll')], default='BLD', max_length=4),
        ),
        migrations.AlterField(
            model_name='pet',
            name='category',
            field=models.CharField(choices=[('DOG', 'Perro'), ('CAT', 'Gato')], default='DOG', max_length=4),
        ),
        migrations.AlterField(
            model_name='pet',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento de la venta.', max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Indica si la venta está habilitada o no.'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='price',
            field=models.DecimalField(decimal_places=2, default=30, help_text='Precio de la venta.', max_digits=5),
            preserve_default=False,
        ),
    ]
