# Generated by Django 4.2.7 on 2023-12-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0013_alter_pet_age_alter_pet_breed_alter_pet_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(default='kora', null=True, upload_to='static/images'),
        ),
    ]
